### ISSUE TITLE
Is there any document about this code?

### ISSUE THREAD

**Issue by xuhenry** [ppizarror/FNELEM-GPU#1]
Dear Ppizarror,
    Is there Any document or gallery about this code?
Thanks!
Best regards,
Henry
@ppizarror

**Comment by ppizarror** [comment]
Hi, I've started this project about 2 weeks ago so there's no gallery or document about this code. Hope I have something finished by the end of this month (because it's part of a homework).

My goal by now, is to try to solve finite element problems, using simple planar membrane elements, calculated by using GPU architecture, matrix stiffness inverse is now being calculated with cuda, and I hope that the calculations on each element will be executed on different threads.

Extending this analysis to different element types being able to solve 3D beam structures, etc.

**Comment by xuhenry** [comment]
Is it only used for the membrane elements? not 3D solid elements?
Thanks a lot!

**Comment by xuhenry** [comment]
Not 3D membrane elements. I say the 3D solid elements, such as tetrahedron element and so on.
Thanks a lot!

**Comment by ppizarror** [comment]
Have you any paper/document related to such elements? Thanks in advance

**Comment by xuhenry** [comment]
Hello, this is some document about the 3D solid in FEM.

Best regards,
Henry
